# Generated by Django 4.1.4 on 2023-01-02 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("visualizer", "0002_alter_stockdata_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockdata",
            name="date_recorded",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
