# Generated by Django 4.1.4 on 2023-03-12 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("visualizer", "0003_stockdata_date_recorded"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.TextField(null=True)),
                (
                    "date_recorded",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data", models.IntegerField()),
            ],
        ),
    ]
