# Generated by Django 4.1.4 on 2023-03-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visualizer", "0004_indexdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexdata",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
